 export const ActionsType={
     SET_PRODUCTS:"SET_PRODUCTS",
     SELECTED_PRODUCTS:"SELECTED_PRODUCTS",
     REMOVE_SELECTED_PRODUCTS:"REMOVE_SELECTED_PRODUCTS ",
     ADD_ITEM_TO_CART:"ADD_ITEM_TO_CART",
    //  DELELTE_ITEM_FROM_CART:"ADELELTE_ITEM_FROM_CART",
 }